
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_blog_development

 
test:
  <<: *default
  database: my_blog_test


production:
  <<: *default
  database: my_blog_production
  username: my_blog
  password: <%= ENV["MY_BLOG_DATABASE_PASSWORD"] %>
